spring:
  datasource:
    username: automobile
    password: automobile
    url: jdbc:mysql://localhost:3306/automobile
  
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    defer-datasource-initialization: true
 
  sql:
    init:
      mode: never